name: Validation
on:
  push:
    branches: ['**'] # Do not run on tags
jobs:
  integrity:
    name: Check integrity
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup PHP
        uses: shivammathur/setup-php@2.1.0
        with:
          php-version: 7.4
          tools: prestissimo
          coverage: none
      - name: Install dependencies
        run: composer install --no-progress --no-suggest --prefer-dist
      - name: Run PHP_CodeSniffer
        run: vendor/bin/phpcs --standard=Mathrix tests/dummy.php
